
package Arayuzler.Hasta;

import DB.*;
import java.sql.*;
import javax.swing.JOptionPane;

public class Bilgilerim extends javax.swing.JPanel {

    private Long kullanici;
    
    public Bilgilerim() {
        initComponents();
    }
    
    public void baslat(){
        setInf();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Kimlik Numarasý:");

        jLabel2.setText("Ad:");

        jLabel3.setText("Soyad:");

        jLabel4.setText("Doðum Yeri:");

        jLabel5.setText("Doðum Tarihi:");

        jLabel6.setText("e-Posta:");

        jLabel7.setText("Telefon Numarasý:");

        jLabel8.setText("Adres");

        jLabel10.setText("Yeni Þifre:");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField7)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(400, 400, 400))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!checkNumber()){
            JOptionPane.showMessageDialog(this, "Numara sadece rakamlardan oluþmalýdýr!");
        }
        else if(jTextField6.getText().length() > 30){
            JOptionPane.showMessageDialog(this, "E-posta adresiniz en fazla 30 haneli olmalýdýr!");
        }
        else if(jTextField8.getText().length() > 30){
            JOptionPane.showMessageDialog(this, "Adresiniz en fazla 30 haneli olmalýdýr!");
        }
        else if(String.valueOf(jPasswordField2.getPassword()).length() > 16){
            JOptionPane.showMessageDialog(this, "Þifreniz en fazla 16 haneli olmalýdýr!");
        }
        else if (!String.valueOf(jPasswordField2.getPassword()).contains(" ")){
            int evet = JOptionPane.showOptionDialog(this,"Bilgilerinizi güncellemeyi onaylýyor musunuz?", "", 0,JOptionPane.INFORMATION_MESSAGE,null,new String[] {"Evet","Hayýr"},null);
            if (evet == 0){
            String eskisifre = (String) JOptionPane.showInputDialog(this,"Þifrenizi giriniz:", "", JOptionPane.INFORMATION_MESSAGE, null, null,null);
            if (eskisifre.length() <= 16){
                Query db = new Query();
                Connection con = db.getCon();
                try {
                    CallableStatement stmt = con.prepareCall("BEGIN\nbilgiupdate(?,?,?,?,?,?,?);\nEND;");
                    stmt.setLong(1, kullanici);
                    stmt.setString(2, jTextField6.getText());
                    stmt.setLong(3, Long.valueOf(jTextField7.getText()));
                    stmt.setString(4, jTextField8.getText());
                    stmt.setString(5, eskisifre);
                    if(String.valueOf(jPasswordField2.getPassword()).equals("")){
                        stmt.setString(6, " ");
                    } else {
                        stmt.setString(6, String.valueOf(jPasswordField2.getPassword()));
                    }
                    stmt.registerOutParameter(7, java.sql.Types.INTEGER);
                    stmt.execute();
                    int basarili = stmt.getInt(7);
                    if (basarili == 0){
                        JOptionPane.showMessageDialog(this, "Bilgileriniz güncellenmiþtir!");
                        setInf();
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Þifreniz yanlýþtýr!");
                    }
                } catch (SQLException ex){
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(this, "Hata oluþtu!");
                }
            }
        }
        }
        else {
            JOptionPane.showMessageDialog(this, "Yeni þifre boþluk barýndýrmamalýdýr!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void setInf(){
        Query db = new Query();
        Connection con = db.getCon();
        try {
            PreparedStatement stmt = con.prepareStatement("SELECT ad, soyad, dogumyeri, dogumtarihi, eposta, telefon, adres FROM hasta WHERE kimlikno=?");
            stmt.setLong(1, kullanici);
            stmt.execute();
            ResultSet result = stmt.executeQuery();
            if(result.next()){
                jLabel11.setText("**"+String.valueOf(kullanici).substring(2,9)+"***");
                jLabel12.setText(result.getString("ad"));
                jLabel13.setText(result.getString("soyad"));
                jLabel14.setText(result.getString("dogumyeri"));
                jLabel15.setText(result.getTimestamp("dogumtarihi").toString().substring(0,11));
                jTextField6.setText(result.getString("eposta"));
                jTextField7.setText(String.valueOf(result.getLong("telefon")));
                jTextField8.setText(result.getString("adres"));
                jPasswordField2.setText("");
            }
        } catch (SQLException ex){
            System.out.println(ex);
        }
    }
    
    private boolean checkNumber(){
        String temp = jTextField7.getText();
        int i = temp.length();
        if(i > 10){
            return false;
        }
        int j = 0;
        
        while(j < i && "0123456789".contains(String.valueOf(temp.charAt(j)))){
            j = j+1;
        }
        return i == j;
    }
    
    public void setKullanici(Long kullanici){
        this.kullanici = kullanici;
    }
    
    protected void setZero(){
        setInf();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
