package Arayuzler.Giris;

import Arayuzler.Doktor.DoktorArayuz;
import Arayuzler.Hasta.HastaArayuz;
import Arayuzler.Yonetici.YoneticiArayuz;
import DB.*;
import java.sql.*;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JPanel {
    
    protected int durum = 0; //0 default durum
                             //1 giris yapma basildi, ve basarili giris yapti

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jLabel1.setText("Kullanýcý Adý:");

        jLabel2.setText("Þifre:");
        jLabel2.setFocusCycleRoot(true);

        jButton1.setText("Giriþ Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kayýt Ol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jPasswordField1.setText("");
        durum = 0;//durum
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jTextField1.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        if(!username.equals("") && !username.equals(" ") && !password.equals("") && !password.equals(" ") && checkNumber(username)){
            Query db = new Query();
            Connection con = db.getCon();
            try {
                CallableStatement stmt = con.prepareCall("BEGIN\ngiriskontrol(?,?,?);\nEND;");
                stmt.setString(1, username);
                stmt.setString(2, password);
                stmt.registerOutParameter(3, java.sql.Types.INTEGER);
                stmt.execute();
                int basarili = stmt.getInt(3);
                if(basarili == 0){
                    YoneticiArayuz yonetici = new YoneticiArayuz();
                    yonetici.baslat();
                    yonetici.setVisible(true);
                    durum = 1;
                    this.setVisible(false);
                }
                else if(basarili == 1){
                    HastaArayuz hasta = new HastaArayuz();
                    hasta.setkullanici(Long.valueOf(username));
                    hasta.setVisible(true);
                    durum = 1;
                    this.setVisible(false);
                 }
                else if(basarili == 2){
                    DoktorArayuz doktor = new DoktorArayuz();
                    doktor.setDoktor(Long.valueOf(username));
                    doktor.setVisible(true);
                    durum = 1;
                    this.setVisible(false);
                }
                else if(basarili == 3){
                    JOptionPane.showMessageDialog(this, "Yanlýþ kullanýcý numarasý veya þifre!");
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Lütfen bilgilerinizi geçerli giriniz!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean checkNumber(String num){
        String temp = num;
        int i = temp.length();
        if(i > 11){
            return false;
        }
        int j = 0;
        
        while(j < i && "0123456789".contains(String.valueOf(temp.charAt(j)))){
            j = j+1;
        }
        return i == j;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
