package Arayuzler.Yonetici;

import DB.Query;
import java.sql.*;
import javax.swing.JOptionPane;

public class KayitEkle extends javax.swing.JPanel {

    
    public KayitEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();

        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });

        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });

        jLabel1.setText("Ýl:");

        jLabel2.setText("Ýlçe:");

        jLabel3.setText("Ad:");

        jLabel4.setText("Adres:");

        jLabel5.setText("Telefon:");

        jLabel6.setText("Hastane Numarasý:");

        jLabel7.setText("Birim Adý:");

        jLabel8.setText("Blok Numarasý:");

        jLabel9.setText("Blok Adý:");

        jLabel10.setText("Kat:");

        jLabel11.setText("Oda Numarasý:");

        jLabel12.setText("Tip:");

        jLabel13.setText("Ad:");

        jLabel14.setText("Soyad:");

        jLabel15.setText("Birim Numarasý:");

        jLabel16.setText("Maaþ:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Kayýt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hasta", "muayene", "laboratuvar", "diger" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(174, 174, 174)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(55, 55, 55)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField4))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel13))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(39, 39, 39)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboBox1, 0, 86, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField11)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(jCheckBox3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Query db = new Query();
        Connection con = db.getCon();
        try {
            if (jCheckBox1.isSelected()){
                if (!checkNumber(jTextField3.getText(), 10)){
                    JOptionPane.showMessageDialog(this, "Telefon numarasý 10 haneli olup, rakamlardan oluþmalýdýr!");
                }
                else if (jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField4.getText().equals("") || jTextField5.getText().equals("") &&
                        jTextField1.getText().equals(" ") || jTextField2.getText().equals(" ") || jTextField3.getText().equals(" ") || jTextField4.getText().equals(" ") || jTextField5.getText().equals(" ")) {
                    JOptionPane.showMessageDialog(this, "Lütfen gerekli alanlarý doldurunuz!");
                }
                else if(jTextField1.getText().length() > 15){
                    JOptionPane.showMessageDialog(this, "Ýl en fazla 15 harfli olmalýdýr!");
                }
                else if(jTextField2.getText().length() > 15){
                    JOptionPane.showMessageDialog(this, "Ýlçe en fazla 15 harfli olmalýdýr!");
                }
                else if(jTextField4.getText().length() > 100){
                    JOptionPane.showMessageDialog(this, "Hastane adý en fazla 100 harfli olmalýdýr!");
                }
                else if(jTextField5.getText().length() > 150){
                    JOptionPane.showMessageDialog(this, "Hastane adresi en fazla 150 harfli olmalýdýr!");
                }
                else if(jTextField1.getText().length() != 0 && jTextField2.getText().length() != 0 && jTextField3.getText().length() != 0 &&
                        jTextField4.getText().length() != 0 && jTextField5.getText().length() != 0){
                    CallableStatement stmt = con.prepareCall("BEGIN\nhastaneKayit(?,?,?,?,?,?);\nEND;");
                    stmt.setString(1, jTextField1.getText());
                    stmt.setString(2, jTextField2.getText());
                    stmt.setString(3, jTextField4.getText());
                    stmt.setString(4, jTextField5.getText());
                    stmt.setLong(5, Long.valueOf(jTextField3.getText()));
                    stmt.registerOutParameter(6, java.sql.Types.INTEGER);
                    stmt.execute();
                    int basarili = stmt.getInt(6);
                    if (basarili == 0){
                        JOptionPane.showMessageDialog(this, "Kayýt baþarýyla eklendi!");
                        hastaneZero();
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Böyle bir kayýt zaten mevcut!");
                    }
                }
            }
            else if (jCheckBox2.isSelected()){
                if (!checkNumber(jTextField6.getText(), 99999)){
                    JOptionPane.showMessageDialog(this, "Hastane numarasý sadece rakamlardan oluþup, en fazla 5 haneli olmalýdýr!");
                }
                else if(jTextField8.getText().length() != 0 && !checkNumber(jTextField8.getText(), 999)){
                    JOptionPane.showMessageDialog(this, "Oda numarasý sadece rakamlardan oluþup, en  fazla 3 haneli olmalýdýr!");
                }
                else if(jTextField11.getText().length() != 0 && !checkNumber(jTextField11.getText(), 99)){
                    JOptionPane.showMessageDialog(this, "Kat numarasý sadece rakamlardan oluþup, en  fazla 2 haneli olmalýdýr!");
                }
                else if(jTextField10.getText().length() > 15){
                    JOptionPane.showMessageDialog(this, "Blok adý en fazla 15 harfli olabilir!");
                }
                else if(jTextField7.getText().length() > 30){
                    JOptionPane.showMessageDialog(this, "Birim adý en fazla 30 harfli olabilir!");
                }
                else if(jTextField9.getText().length() > 2){
                    JOptionPane.showMessageDialog(this, "Blok numarasý en fazla 2 harfli olabilir!");
                }
                else if(!jTextField6.getText().equals("") && !jTextField7.getText().equals("")){
                    if(jTextField8.getText().equals("")){
                        jTextField8.setText("-99");
                    }
                    if(jTextField9.getText().equals("")){
                        jTextField9.setText(" ");
                    }
                    if(jTextField10.getText().equals("")){
                        jTextField10.setText(" ");
                    }
                    if(jTextField11.getText().equals("")){
                        jTextField11.setText("-99");
                    }
                    CallableStatement stmt = con.prepareCall("BEGIN\nbirimKayit(?,?,?,?,?,?,?,?);\nEND;");
                    stmt.setLong(1, Long.valueOf(jTextField6.getText()));
                    stmt.setString(2, jTextField7.getText());
                    stmt.setString(3, jTextField9.getText());
                    stmt.setString(4, jTextField10.getText());
                    stmt.setInt(5, Integer.parseInt(jTextField11.getText()));
                    stmt.setInt(6, Integer.parseInt(jTextField8.getText()));
                    stmt.setString(7, (String) jComboBox1.getSelectedItem());
                    stmt.registerOutParameter(8, java.sql.Types.INTEGER);
                    stmt.execute();
                    int basarili = stmt.getInt(8);
                    if (basarili == 0){
                        JOptionPane.showMessageDialog(this, "Kayýt baþarýyla eklendi!");
                        birimZero();
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Geçersiz hastane numarasý!");
                    }
                }
            }
            else if (jCheckBox3.isSelected()){
                if(jTextField12.getText().length() > 15){
                    JOptionPane.showMessageDialog(this, "Personel adý en fazla 15 haneli olabilir!");
                }
                else if(jTextField13.getText().length() > 15){
                    JOptionPane.showMessageDialog(this, "Personel soyadý en fazla 15 haneli olabilir!");
                }
                else if(jTextField14.getText().length() != 0 && !checkNumber(jTextField14.getText(), 999999)){
                    JOptionPane.showMessageDialog(this, "Birim numarasý rakamlardan oluþup, en fazla 6 haneli olmalýdýr!");
                }
                else if(jTextField15.getText().length() != 0 && !checkNumber(jTextField15.getText(), 99999)){
                    JOptionPane.showMessageDialog(this, "Birim numarasý rakamlardan oluþup, en fazla 99.999,99 olmalýdýr!");
                }
                else if(jTextField12.getText().length() != 0 && jTextField13.getText().length() != 0 && jTextField14.getText().length() != 0 && jTextField15.getText().length() != 0){
                    CallableStatement stmt = con.prepareCall("BEGIN\npersonelKayit(?,?,?,?,?);\nEND;");
                    stmt.setString(1, jTextField12.getText());
                    stmt.setString(2, jTextField13.getText());
                    stmt.setLong(3, Long.valueOf(jTextField14.getText()));
                    stmt.setInt(4, Integer.valueOf(jTextField15.getText()));
                    stmt.registerOutParameter(5, java.sql.Types.INTEGER);
                    stmt.execute();
                    int basarili = stmt.getInt(5);
                    if (basarili == 0){
                        JOptionPane.showMessageDialog(this, "Kayýt baþarýyla eklendi!");
                        personelZero();
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Geçersiz birim numarasý!");
                    }
                }
            }
        } catch (SQLException ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Hata oluþtu!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        jCheckBox1.setSelected(true);
        if(!jTextField1.isEnabled()){
            hastaneEnable();
        }
        jCheckBox2.setSelected(false);
        if(jTextField6.isEnabled()){
            birimDisable();
        }
        jCheckBox3.setSelected(false);
        if(jTextField12.isEnabled()){
            personelDisable();
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        jCheckBox2.setSelected(true);
        if(!jTextField6.isEnabled()){
            birimEnable();
        }
        jCheckBox1.setSelected(false);
        if(jTextField1.isEnabled()){
            hastaneDisable();
        }
        jCheckBox3.setSelected(false);
        if(jTextField12.isEnabled()){
            personelDisable();
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        jCheckBox3.setSelected(true);
        if(!jTextField12.isEnabled()){
            personelEnable();
        }
        jCheckBox1.setSelected(false);
        if(jTextField6.isEnabled()){
            birimDisable();
        }
        jCheckBox2.setSelected(false);
        if(jTextField1.isEnabled()){
            hastaneDisable();
        }
    }//GEN-LAST:event_jCheckBox3MouseClicked
    
    private boolean checkNumber(String num, int max){
        String temp = num;
        int i = temp.length();
        if(i > max){
            return false;
        }
        int j = 0;
        
        while(j < i && "0123456789".contains(String.valueOf(temp.charAt(j)))){
            j = j+1;
        }
        return i == j;
    }
    
    private void hastaneZero(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }
    
    private void birimZero(){
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jComboBox1.setSelectedIndex(0);
    }
    
    private void personelZero(){
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
    }
    
    private void hastaneDisable(){
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
    }
    
    private void birimDisable(){
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField10.setEnabled(false);
        jTextField11.setEnabled(false);
        jComboBox1.setEnabled(false);
    }
    
    private void personelDisable(){
        jTextField12.setEnabled(false);
        jTextField13.setEnabled(false);
        jTextField14.setEnabled(false);
        jTextField15.setEnabled(false);
    }
    
    private void hastaneEnable(){
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
    }
    
    private void birimEnable(){
        jTextField6.setEnabled(true);
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true);
        jTextField9.setEnabled(true);
        jTextField10.setEnabled(true);
        jTextField11.setEnabled(true);
        jComboBox1.setEnabled(true);
    }
    
    private void personelEnable(){
        jTextField12.setEnabled(true);
        jTextField13.setEnabled(true);
        jTextField14.setEnabled(true);
        jTextField15.setEnabled(true);
    }
    public void baslat(){
        jCheckBox1MouseClicked(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
